// UI strings for the eSIM store and install page. English and French; Kreol
// readers get French, because the phone screens they will be following are in
// French or English, never Kreol (lib/email.ts makes the same call).

export type UiLang = "en" | "fr";

export const toUiLang = (l: string | null | undefined): UiLang => (l === "en" || !l ? "en" : "fr");

export const COPY = {
  en: {
    eyebrow: "MAURITIUS · RODRIGUES",
    h1: "Mobile data on Rodrigues, before you land",
    sub: "An instant eSIM on my.t 4G — the network that actually covers Rodrigues. No SIM shop, no queue, no passport photocopy. Install it at home; it starts when you arrive.",
    trust: ["Delivered in seconds", "my.t 4G on Rodrigues", "Hotspot included", "Keep your WhatsApp number"],
    plansTitle: "Choose your data",
    plansNote: "All prices are final. Paid by card or PayPal.",
    badges: { popular: "Our pick", best_value: "Best value", short_trip: "Short stay", long_stay: "Heavy use" } as Record<string, string>,
    choose: "Choose",
    perGb: "per GB",
    abroad: (n: number) => `+ ${n} countries`,
    noPlans: "Plans are being updated. Please check back in a few minutes.",
    loadError: "We couldn't load the plans just now. Please refresh the page.",
    howTitle: "How it works",
    how: [
      { t: "Buy in a minute", b: "Choose a plan, pay by card or PayPal. Your eSIM appears on screen and in your inbox straight away." },
      { t: "Install at home", b: "On Wi-Fi, before you fly. One tap on iPhone, or scan the QR code. The days don't start yet." },
      { t: "Land and switch on", b: "Turn on data roaming for the eSIM. It connects to my.t and your plan starts." },
    ],
    netTitle: "Why the network matters here",
    netBody:
      "Mauritius has three mobile networks, and only two of them reach Rodrigues: my.t and Emtel. Chili has no signal on the island — so a “Mauritius eSIM” that runs on Chili works in Port Louis and goes dead the moment you land at Plaine Corail. Every plan we sell connects to my.t 4G, and we check each one against the supplier's network list before it goes on sale.",
    netCoverage:
      "Coverage is strong around Port Mathurin, the villages and the main roads; expect weaker signal in some deep valleys and out on the lagoon islets such as Île aux Cocos.",
    compatTitle: "Will it work on my phone?",
    compatTest: "The test that is never wrong: dial *#06#. If you see an “EID” number, your phone takes eSIMs.",
    compatUnlocked: "It must also be carrier-unlocked. Phones sold in mainland China, Hong Kong and Macau usually have no eSIM.",
    compatSearch: "Search your model, e.g. iPhone 13",
    compatNone: "Not on our list — try the *#06# test above before buying.",
    faqTitle: "Questions travellers ask",
    findTitle: "Already bought one?",
    findBody: "Enter your order number and email to open your install page again.",
    findRef: "Order number (ES-…)",
    findEmail: "Email used to pay",
    findGo: "Find my eSIM",
    alsoTitle: "Sort the rest of your arrival",
    also: [
      { href: "/transfers", label: "Airport transfer from Plaine Corail" },
      { href: "/browse/scooter", label: "Rent a scooter for the island" },
      { href: "/guide/rodrigues", label: "The Rodrigues travel guide" },
    ],
    // Checkout
    sheetTitle: "Your eSIM",
    email: "Email",
    emailHelp: "Your QR code and install link are sent here.",
    emailBad: "Please enter a valid email — your eSIM is sent there.",
    compatConfirm: "My phone supports eSIM and is unlocked",
    compatConfirmNeeded: "Please confirm your phone supports eSIM.",
    compatCheck: "Not sure? Check",
    payLoading: "Loading secure payment…",
    payFail: "The payment could not start. You have not been charged — please try again.",
    processing: "Payment received — preparing your eSIM…",
    processingSub: "This usually takes a few seconds. Please keep this page open.",
    secure: "Secure payment by PayPal · card accepted, no account needed",
    guarantee: "If we can't deliver your eSIM, you get a full refund.",
    close: "Close",
    soonTitle: "eSIM sales open very soon",
    soonBody: "Leave your email and we'll tell you the moment you can buy.",
    soonCta: "Notify me",
    soonDone: "Thank you — we'll email you as soon as it opens.",
    // ── Other destinations (M224) ──
    world: {
      eyebrow: (name: string) => `eSIM · ${name.toUpperCase()}`,
      h1: (inPlace: string) => `Mobile data ${inPlace}, before you land`,
      sub: (name: string, _inPlace: string) =>
        `An instant eSIM for ${name}: pay in a minute, install it at home, and it connects to a local network the moment you arrive. No SIM shop, no roaming bill.`,
      localNetworks: "Local 4G/5G networks",
      netTitle: (inPlace: string) => `Which network you get ${inPlace}`,
      netBody: (list: string, inPlace: string) => `This eSIM connects to ${list} ${inPlace}, whichever has the best signal where you are.`,
      alsoTitle: "Before or after Rodrigues",
      also: [
        { href: "/esim", label: "The Mauritius & Rodrigues eSIM (my.t 4G)" },
        { href: "/transfers", label: "Airport transfer from Plaine Corail" },
        { href: "/guide/rodrigues", label: "The Rodrigues travel guide" },
      ],
    },
    destTitleHome: "Travelling beyond Mauritius?",
    destSubHome: "eSIMs for the places Rodrigues travellers pass through or fly home to — same instant delivery, same install page.",
    destTitleWorld: "Other destinations",
    destSubWorld: "Every eSIM in the store, delivered the same way.",
    destFrom: (price: string) => `from ${price}`,
    destSearch: "Search a country",
    destNone: "Not on our list yet. Tell us where you're going on WhatsApp and we'll add it.",
    // ── Boarding-pass design (M225) ──
    heroCta: (price: string) => `See plans · from ${price}`,
    heroCtaNoPrice: "See plans",
    heroCompat: "Will my phone work?",
    islandTime: "Rodrigues time",
    chips: { plans: "Plans", how: "How it works", net: "Network", compat: "Phone check", faq: "FAQ", dest: "Other countries" },
    pass: "DATA PASS",
    perDayDays: (days: string) => `per day · ${days}`,
    boardOperator: "Operator",
    boardRodrigues: "On Rodrigues",
    boardCovered: "Covered",
    boardNoSignal: "No signal",
    boardNetwork: "Network",
    boardNote: "Every plan in this store connects to my.t 4G.",
    howSteps: ["Buy in a minute", "Install at home", "Land and switch on"],
    compatDial: "Dial",
    compatCleared: "An EID number appears? Your phone takes eSIMs.",
    barFrom: (price: string) => `From ${price}`,
    barSub: "Instant QR · hotspot included",
    barCta: "See plans",
    help: "Questions? Ask us on WhatsApp",
    helpShort: "WhatsApp",
    helpMsg: (plan: string, inPlace: string) => `Hello! A question about the ${plan} eSIM for use ${inPlace}.`,
    helpMsgGeneric: "Hello! A question about the eSIM.",
    payTitle: "Pay securely",
    payMethods: "Visa · Mastercard · Amex · PayPal — no PayPal account needed",
  },
  fr: {
    eyebrow: "MAURICE · RODRIGUES",
    h1: "Internet mobile à Rodrigues, dès l'atterrissage",
    sub: "Une eSIM instantanée sur my.t 4G — le réseau qui couvre vraiment Rodrigues. Pas de boutique, pas de file, pas de photocopie de passeport. Installez-la chez vous ; elle démarre à votre arrivée.",
    trust: ["Livrée en quelques secondes", "my.t 4G à Rodrigues", "Partage de connexion inclus", "Gardez votre numéro WhatsApp"],
    plansTitle: "Choisissez vos données",
    plansNote: "Prix finaux. Paiement par carte ou PayPal.",
    badges: { popular: "Notre choix", best_value: "Meilleur prix", short_trip: "Court séjour", long_stay: "Gros usage" } as Record<string, string>,
    choose: "Choisir",
    perGb: "le Go",
    abroad: (n: number) => `+ ${n} pays`,
    noPlans: "Les forfaits sont en cours de mise à jour. Revenez dans quelques minutes.",
    loadError: "Impossible de charger les forfaits pour le moment. Rechargez la page.",
    howTitle: "Comment ça marche",
    how: [
      { t: "Achetez en une minute", b: "Choisissez un forfait, payez par carte ou PayPal. Votre eSIM s'affiche à l'écran et arrive par email aussitôt." },
      { t: "Installez chez vous", b: "En Wi-Fi, avant le départ. Un geste sur iPhone, ou scannez le QR code. Les jours ne comptent pas encore." },
      { t: "Atterrissez et activez", b: "Activez l'itinérance des données pour l'eSIM. Elle se connecte à my.t et votre forfait démarre." },
    ],
    netTitle: "Pourquoi le réseau compte ici",
    netBody:
      "Maurice a trois réseaux mobiles, et seuls deux atteignent Rodrigues : my.t et Emtel. Chili n'a aucun signal sur l'île — une « eSIM Maurice » sur Chili marche à Port-Louis et s'éteint dès l'atterrissage à Plaine Corail. Tous nos forfaits se connectent à my.t 4G, et chacun est vérifié sur la liste des réseaux du fournisseur avant d'être mis en vente.",
    netCoverage:
      "La couverture est bonne autour de Port-Mathurin, des villages et des routes principales ; le signal peut faiblir au fond de certaines vallées et sur les îlots du lagon comme l'Île aux Cocos.",
    compatTitle: "Mon téléphone est-il compatible ?",
    compatTest: "Le test infaillible : composez *#06#. Si un numéro « EID » s'affiche, votre téléphone accepte les eSIM.",
    compatUnlocked: "Il doit aussi être désimlocké. Les téléphones vendus en Chine continentale, à Hong Kong et Macao n'ont généralement pas d'eSIM.",
    compatSearch: "Cherchez votre modèle, ex. iPhone 13",
    compatNone: "Absent de notre liste — faites le test *#06# ci-dessus avant d'acheter.",
    faqTitle: "Les questions des voyageurs",
    findTitle: "Déjà acheté ?",
    findBody: "Entrez votre numéro de commande et votre email pour rouvrir votre page d'installation.",
    findRef: "Numéro de commande (ES-…)",
    findEmail: "Email utilisé pour payer",
    findGo: "Retrouver mon eSIM",
    alsoTitle: "Organisez le reste de votre arrivée",
    also: [
      { href: "/fr/taxi-rodrigues", label: "Taxi et transfert depuis l'aéroport" },
      { href: "/fr/location-scooter-rodrigues", label: "Louer un scooter à Rodrigues" },
      { href: "/fr/se-deplacer-a-rodrigues", label: "Se déplacer à Rodrigues" },
    ],
    sheetTitle: "Votre eSIM",
    email: "Email",
    emailHelp: "Votre QR code et votre lien d'installation y sont envoyés.",
    emailBad: "Entrez un email valide — votre eSIM y est envoyée.",
    compatConfirm: "Mon téléphone accepte l'eSIM et est désimlocké",
    compatConfirmNeeded: "Confirmez que votre téléphone accepte l'eSIM.",
    compatCheck: "Pas sûr ? Vérifier",
    payLoading: "Chargement du paiement sécurisé…",
    payFail: "Le paiement n'a pas pu démarrer. Vous n'avez pas été débité — réessayez.",
    processing: "Paiement reçu — préparation de votre eSIM…",
    processingSub: "Cela prend généralement quelques secondes. Gardez cette page ouverte.",
    secure: "Paiement sécurisé par PayPal · carte acceptée, sans compte",
    guarantee: "Si nous ne pouvons pas livrer votre eSIM, vous êtes remboursé intégralement.",
    close: "Fermer",
    soonTitle: "La vente d'eSIM ouvre très bientôt",
    soonBody: "Laissez votre email, nous vous prévenons dès l'ouverture.",
    soonCta: "Me prévenir",
    soonDone: "Merci — nous vous écrivons dès l'ouverture.",
    world: {
      eyebrow: (name: string) => `eSIM · ${name.toUpperCase()}`,
      h1: (inPlace: string) => `Internet mobile ${inPlace}, dès l'atterrissage`,
      // French countries take articles ("la France", "les Seychelles"), so
      // the sentence uses the stored preposition form ("en France",
      // "aux Seychelles") instead of the bare name.
      sub: (_name: string, inPlace: string) =>
        `Une eSIM instantanée à utiliser ${inPlace} : payez en une minute, installez-la chez vous, et elle se connecte à un réseau local dès votre arrivée. Pas de boutique, pas de facture d'itinérance.`,
      localNetworks: "Réseaux locaux 4G/5G",
      netTitle: (inPlace: string) => `Le réseau utilisé ${inPlace}`,
      netBody: (list: string, inPlace: string) => `Cette eSIM se connecte à ${list} ${inPlace}, selon le meilleur signal là où vous êtes.`,
      alsoTitle: "Avant ou après Rodrigues",
      also: [
        { href: "/fr/esim-maurice-rodrigues", label: "L'eSIM Maurice et Rodrigues (my.t 4G)" },
        { href: "/fr/taxi-rodrigues", label: "Taxi et transfert depuis l'aéroport" },
        { href: "/fr/guide-rodrigues", label: "Le guide de Rodrigues" },
      ],
    },
    destTitleHome: "Vous voyagez au-delà de Maurice ?",
    destSubHome: "Des eSIM pour les pays où passent les voyageurs de Rodrigues — même livraison instantanée, même page d'installation.",
    destTitleWorld: "Autres destinations",
    destSubWorld: "Toutes les eSIM de la boutique, livrées de la même façon.",
    destFrom: (price: string) => `dès ${price}`,
    destSearch: "Chercher un pays",
    destNone: "Pas encore dans notre liste. Dites-nous où vous allez sur WhatsApp, nous l'ajouterons.",
    heroCta: (price: string) => `Voir les forfaits · dès ${price}`,
    heroCtaNoPrice: "Voir les forfaits",
    heroCompat: "Mon téléphone est-il compatible ?",
    islandTime: "Heure de Rodrigues",
    chips: { plans: "Forfaits", how: "Comment ça marche", net: "Réseau", compat: "Compatibilité", faq: "Questions", dest: "Autres pays" },
    pass: "PASS DATA",
    perDayDays: (days: string) => `par jour · ${days}`,
    boardOperator: "Opérateur",
    boardRodrigues: "À Rodrigues",
    boardCovered: "Couvert",
    boardNoSignal: "Aucun signal",
    boardNetwork: "Réseau",
    boardNote: "Tous les forfaits de cette boutique se connectent à my.t 4G.",
    howSteps: ["Achetez en une minute", "Installez chez vous", "Atterrissez et activez"],
    compatDial: "Composez",
    compatCleared: "Un numéro EID s'affiche ? Votre téléphone accepte les eSIM.",
    barFrom: (price: string) => `Dès ${price}`,
    barSub: "QR instantané · partage inclus",
    barCta: "Forfaits",
    help: "Une question ? Écrivez-nous sur WhatsApp",
    helpShort: "WhatsApp",
    helpMsg: (plan: string, inPlace: string) => `Bonjour ! Une question sur l'eSIM ${plan} à utiliser ${inPlace}.`,
    helpMsgGeneric: "Bonjour ! Une question sur l'eSIM.",
    payTitle: "Paiement sécurisé",
    payMethods: "Visa · Mastercard · Amex · PayPal — sans compte PayPal",
  },
};

export type Copy = (typeof COPY)["en"];
