-- ═══════════════════════════════════════════════════════════════════════════
-- M223 · THE eSIM STORE
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Visitors buy a Mauritius data eSIM on /esim, pay by PayPal (EUR), and get a
-- QR code + one-tap install link seconds later. We are a RESELLER: the eSIM
-- is bought from a wholesaler (lib/esim/providers) only after the customer's
-- payment has been captured, so the platform never pays for an eSIM nobody
-- bought.
--
-- Three tables, all SERVER-ONLY. Every read and write goes through a route
-- holding the service-role key; anon and authenticated have no grant on any of
-- them. The one public read — the catalogue — is a security-definer function
-- returning exactly the columns a shopper may see (never the wholesale cost).
--
-- MONEY UNITS ARE IN THE COLUMN NAMES (this codebase has shipped a
-- rupees-vs-cents bug twice): *_eur_cents is what the customer pays,
-- *_usd_micros is what the wholesaler charges us (millionths of a USD).

-- ── Plans ────────────────────────────────────────────────────────────────────
create table if not exists public.esim_plans (
  id                    uuid primary key default gen_random_uuid(),
  provider              text not null,
  provider_code         text not null,
  provider_slug         text,
  -- 'mauritius' today; 'reunion', 'madagascar', 'europe'... later. A region
  -- is what the shopper chooses; country_codes is what the plan covers.
  region                text not null default 'mauritius',
  country_codes         text[] not null default array['MU'],
  name                  text not null,
  data_mb               integer not null check (data_mb > 0),
  -- A daily plan resets data_mb every 24h; a fixed plan has data_mb in total.
  per_day               boolean not null default false,
  -- Day passes are ONE wholesale package bought for N days (eSIM Access
  -- `periodNum`); a "7-day, 1GB a day" product is package MU_1_Daily × 7.
  -- Null for a fixed plan, where the package itself carries its validity.
  period_num            integer check (period_num is null or period_num between 1 and 365),
  validity_days         integer not null check (validity_days between 1 and 366),
  -- What happens after a daily allowance runs out, e.g. "384 Kbps".
  fup_policy            text,
  -- Where the traffic exits to the internet, e.g. "UK/NO". Shown in the FAQ:
  -- a site that geolocates will think the visitor is in the UK or Norway.
  ip_export             text,
  -- [{"name":"Emtel","type":"4G"}, …] exactly as the wholesaler reported.
  networks              jsonb not null default '[]'::jsonb,
  -- Computed by lib/esim/networks.ts at sync time. A plan that cannot be
  -- shown to roam onto my.t or Emtel is NEVER shown: Chili has no signal on
  -- Rodrigues, and an MTML-only plan is a dead eSIM there.
  covers_rodrigues      boolean not null default false,
  hotspot               boolean not null default true,
  topup_supported       boolean not null default false,
  wholesale_usd_micros  bigint not null check (wholesale_usd_micros > 0),
  retail_eur_cents      integer not null check (retail_eur_cents > 0),
  -- True once the owner has typed a price: a sync then never overwrites it.
  retail_locked         boolean not null default false,
  active                boolean not null default false,
  badge                 text check (badge is null or badge in ('popular','best_value','short_trip','long_stay')),
  sort_order            integer not null default 100,
  -- Still offered by the wholesaler as of the last sync. A plan they retired
  -- stays in the table (orders reference it) but cannot be bought.
  available             boolean not null default true,
  synced_at             timestamptz,
  provider_payload      jsonb,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);

-- One product per (package, number of days). coalesce() because two NULLs
-- are never equal to a unique constraint, which would let a sync insert the
-- same fixed plan twice.
create unique index if not exists esim_plans_product_uidx
  on public.esim_plans (provider, provider_code, coalesce(period_num, 0));

create index if not exists esim_plans_shop_idx
  on public.esim_plans (region, sort_order)
  where active and available and covers_rodrigues;

-- ── Orders ───────────────────────────────────────────────────────────────────
create table if not exists public.esim_orders (
  -- Generated by the server, never by the database: the same value is PayPal's
  -- reference_id and the wholesaler's transactionId, which is what makes a
  -- retried purchase idempotent end to end. See lib/esim/ids.ts.
  id                    uuid primary key,
  ref                   text not null unique check (ref ~ '^ES-[0-9A-F]{6}$'),
  access_token_hash     text not null check (length(access_token_hash) = 64),
  plan_id               uuid not null references public.esim_plans(id) on delete restrict,
  -- What was sold, frozen: the plan row may be repriced or renamed tomorrow.
  plan_snapshot         jsonb not null,
  email                 text not null check (email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' and length(email) <= 254),
  language              text not null default 'en' check (language in ('en','fr','cr')),
  status                text not null default 'pending_payment' check (status in (
                          'pending_payment',  -- PayPal order created, not captured
                          'paid',             -- captured, wholesaler not yet asked
                          'provisioning',     -- wholesaler has our order, profile not back
                          'delivered',        -- activation code stored, customer can install
                          'failed',           -- wholesaler refused; owner must refund or retry
                          'refunded',
                          'cancelled')),      -- never paid
  retail_eur_cents      integer not null check (retail_eur_cents > 0),
  wholesale_usd_micros  bigint,
  paypal_order_id       text unique,
  paypal_capture_id     text unique,
  paid_eur_cents        integer,
  provider              text not null,
  provider_order_no     text unique,
  iccid                 text,
  lpa                   text,
  smdp_address          text,
  activation_code       text,
  qr_code_url           text,
  esim_status           text,
  expires_at            timestamptz,
  total_bytes           bigint,
  used_bytes            bigint,
  usage_checked_at      timestamptz,
  provision_attempts    integer not null default 0,
  last_error            text,
  email_sent_at         timestamptz,
  -- utm_*, referrer, landing path, bundle (future: "rented a scooter too").
  source                jsonb not null default '{}'::jsonb,
  created_at            timestamptz not null default now(),
  paid_at               timestamptz,
  delivered_at          timestamptz,
  refunded_at           timestamptz,
  updated_at            timestamptz not null default now()
);

create index if not exists esim_orders_created_idx on public.esim_orders (created_at desc);
create index if not exists esim_orders_email_idx on public.esim_orders (lower(email));
create index if not exists esim_orders_open_idx on public.esim_orders (status)
  where status in ('paid','provisioning','failed');

-- ── Webhook events ───────────────────────────────────────────────────────────
-- Every notification the wholesaler sends, kept verbatim. event_key makes a
-- redelivered webhook a no-op; the payload is evidence when a customer says
-- "it never arrived" and the wholesaler says it did.
create table if not exists public.esim_webhook_events (
  id            bigint generated always as identity primary key,
  provider      text not null,
  event_key     text not null unique,
  event_type    text,
  order_no      text,
  iccid         text,
  payload       jsonb not null,
  signature_ok  boolean,
  received_at   timestamptz not null default now(),
  processed_at  timestamptz,
  error         text
);

create index if not exists esim_webhook_events_order_idx on public.esim_webhook_events (order_no);

-- ── updated_at ───────────────────────────────────────────────────────────────
drop trigger if exists t_esim_plans_updated on public.esim_plans;
create trigger t_esim_plans_updated before update on public.esim_plans
  for each row execute function set_updated_at();
drop trigger if exists t_esim_orders_updated on public.esim_orders;
create trigger t_esim_orders_updated before update on public.esim_orders
  for each row execute function set_updated_at();

-- ── Server-only ──────────────────────────────────────────────────────────────
-- RLS on with NO policies, and no grants: the service role bypasses both, and
-- nothing else can read an activation code, an email or a wholesale price.
alter table public.esim_plans          enable row level security;
alter table public.esim_orders         enable row level security;
alter table public.esim_webhook_events enable row level security;
revoke all on public.esim_plans, public.esim_orders, public.esim_webhook_events from anon, authenticated;
-- Explicit, not assumed from default privileges: a table the service role
-- cannot touch fails as "permission denied" only on the first real order.
grant select, insert, update, delete on public.esim_plans, public.esim_orders, public.esim_webhook_events to service_role;

-- ── The public catalogue ─────────────────────────────────────────────────────
-- What a shopper may see and nothing else: no wholesale cost, no provider
-- payload. Filters are here, not in the page, so no caller can forget the
-- Rodrigues rule.
create or replace function public.public_esim_plans(p_region text default 'mauritius')
returns table (
  id uuid, name text, region text, country_codes text[], data_mb integer, per_day boolean,
  validity_days integer, networks jsonb, hotspot boolean, topup_supported boolean,
  fup_policy text, ip_export text, retail_eur_cents integer, badge text, sort_order integer
)
language sql stable security definer set search_path = public, pg_temp as $$
  select p.id, p.name, p.region, p.country_codes, p.data_mb, p.per_day,
         p.validity_days, p.networks, p.hotspot, p.topup_supported,
         p.fup_policy, p.ip_export, p.retail_eur_cents, p.badge, p.sort_order
    from public.esim_plans p
   where p.region = p_region
     and p.active and p.available and p.covers_rodrigues
   order by p.sort_order, p.retail_eur_cents;
$$;

revoke all on function public.public_esim_plans(text) from public;
grant execute on function public.public_esim_plans(text) to anon, authenticated, service_role;

-- A new function is invisible to PostgREST until its schema cache reloads, and
-- the symptom is an EMPTY catalogue with no error (see the schema-cache trap).
notify pgrst, 'reload schema';

do $$
begin
  assert (select relrowsecurity from pg_class where oid = 'public.esim_orders'::regclass),
    'esim_orders must have RLS enabled';
  assert not has_table_privilege('anon', 'public.esim_orders', 'SELECT'),
    'anon must not read esim_orders';
  assert not has_table_privilege('authenticated', 'public.esim_plans', 'SELECT'),
    'authenticated must not read esim_plans directly (wholesale cost)';
  assert has_function_privilege('anon', 'public.public_esim_plans(text)', 'EXECUTE'),
    'anon must be able to read the public catalogue';
end $$;
