-- ═══════════════════════════════════════════════════════════════════════════
-- M211 — THE DOCUMENT HE MAKES BY HAND
-- ═══════════════════════════════════════════════════════════════════════════
--
-- The owner already sends this: a booking confirmation for an excursion, with
-- the guest, the meeting point, a priced line, a 50% deposit and a payment
-- status. He types it. The reference on the one he showed — RR-COCOS-SB — is
-- his own, not generated by anything here.
--
-- ── WHY THIS IS NOT AN INVOICE ROW ────────────────────────────────────────
--
-- invoices was built to record a figure READ from a source row, and three of
-- its NOT NULL columns exist only to prove that reading: source_amount_unit,
-- source_amount_raw, source_total_cents, checked against each other by
-- invoices_unit_provenance. A document the owner composes has no source row.
-- Filling those columns with the typed total would be asserting a provenance
-- that does not exist — in the one column set built to stop exactly that.
--
-- Two more would have to be bent: subject_type and subject_id are NOT NULL and
-- a walk-in has neither, and the guard trigger makes an issued invoice
-- immutable while this document is edited until it is sent.
--
-- So it is its own table, sharing the one thing worth sharing: next_invoice_seq
-- allocates its numbers, in its own 'BKG' series, so a booking document and an
-- invoice can never collide on a number.
--
-- ── WHAT THE PLATFORM CANNOT TELL HIM ─────────────────────────────────────
--
-- Almost all of it, which is why the columns are free text rather than joins:
--
--   meeting point  does not exist anywhere in the schema or the content model
--   meeting time   place_bookings has time_slot, a band ("Morning"), not 09:00
--   unit price     place_bookings prices FLAT per reservation; "2 x Rs 1,800"
--                  has no source column and nothing multiplies by guests
--   deposit        removed from experiences on 2026-08-13 — "paid in full at
--                  the point of booking" — so a deposit here is his
--                  arrangement with one customer, not a site rule
--
-- place_booking_id is therefore a PREFILL HINT, nullable and unenforced. It
-- records which reservation a document was started from when there was one. It
-- never makes this document authoritative over that row, and nothing reads
-- back from here into place_bookings.

create table if not exists public.booking_documents (
  id             uuid primary key default gen_random_uuid(),

  -- Numbering, from the same counter the invoice series uses.
  series         text        not null default 'BKG' check (series = 'BKG'),
  issue_year     smallint    not null check (issue_year between 2026 and 2100),
  seq            integer     not null check (seq > 0),
  number         text        not null,

  -- HIS reference, typed, printed in the header where the customer looks.
  -- Deliberately free text: RR-COCOS-SB is not the RR-XXXXXX six-hex shape
  -- that /track and /manage-booking validate, and this document is not looked
  -- up there.
  reference      text        not null check (btrim(reference) <> ''),

  guest_name     text        not null check (btrim(guest_name) <> ''),
  guest_email    text,
  guest_phone    text,

  -- The detail rows, in the order they are printed. [{label, value}]
  details        jsonb       not null default '[]'::jsonb,

  -- Money. INTEGER MINOR UNITS, like everything else that reaches a document.
  total_cents    integer     not null default 0 check (total_cents   >= 0),
  deposit_pct    integer                  check (deposit_pct between 0 and 100),
  deposit_cents  integer     not null default 0 check (deposit_cents >= 0),
  received_cents integer     not null default 0 check (received_cents >= 0),

  constraint booking_documents_deposit_within_total
    check (deposit_cents <= total_cents),

  -- Snapshotted at save, like invoices snapshot the seller. If he changes his
  -- Juice number next year, a document already sent still says what it said.
  pay_instruction text,
  note            text,

  place_booking_id uuid references public.place_bookings(id) on delete set null,

  state          text        not null default 'open'
                             check (state in ('open', 'cancelled')),
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now(),

  constraint booking_documents_number_unique unique (number),
  constraint booking_documents_seq_unique    unique (series, issue_year, seq)
);

create index if not exists booking_documents_recent_idx
  on public.booking_documents (created_at desc);

create table if not exists public.booking_document_lines (
  id               uuid primary key default gen_random_uuid(),
  document_id      uuid not null references public.booking_documents(id) on delete cascade,
  position         integer not null check (position > 0),
  description      text    not null check (btrim(description) <> ''),
  qty              numeric(12,3) not null check (qty > 0),
  unit_price_cents integer not null check (unit_price_cents >= 0),
  line_total_cents integer not null check (line_total_cents >= 0),

  -- The same arithmetic guard invoice_lines carries.
  constraint booking_document_lines_arithmetic
    check (line_total_cents = round(qty * unit_price_cents)),
  constraint booking_document_lines_position_unique unique (document_id, position)
);

-- ── Locked down, like every other money table here ─────────────────────────
-- RLS on with NO policy denies every command to anon and authenticated, and
-- the grants below are the door service_role comes through.
alter table public.booking_documents      enable row level security;
alter table public.booking_document_lines enable row level security;

revoke all on table public.booking_documents      from anon, authenticated;
revoke all on table public.booking_document_lines from anon, authenticated;
grant select, insert, update, delete on public.booking_documents      to service_role;
grant select, insert, update, delete on public.booking_document_lines to service_role;

-- ── The seller's payment instruction ───────────────────────────────────────
-- "MCB Juice: 58363401" is the owner's own phone number — that is what a Juice
-- account IS — so it is a setting he fills in, never a literal in the source.
-- BankTransferDetails.tsx hard-codes an account number; that is the pattern
-- this deliberately does not copy.
alter table public.invoice_settings
  add column if not exists pay_instruction text;

comment on column public.invoice_settings.pay_instruction is
  'One line telling a customer how to pay, in the owner''s own words, e.g. "MCB Juice: 58363401". Snapshotted onto each booking document at save.';

notify pgrst, 'reload schema';
